apiVersion: v1
kind: Namespace
metadata:
  name: podinfo2
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo2
  namespace: podinfo2
  labels:
    app: podinfo2
spec:
  type: ClusterIP
  selector:
    app: podinfo2
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: podinfo2
  labels:
    app: podinfo2
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo2
    spec:
      initContainers:
      - name: init
        image: alpine:3.10
        command:
        - sleep
        - "1"
      containers:
      - name: podinfod
        image: stefanprodan/podinfo:2.1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_MESSAGE
          value: "Greetings robot!"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo2-cfg
  namespace: podinfo2
  labels:
    app: podinfo2
data:
  configval1: hello
  configval2: world
---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo2-secrets
  namespace: podinfo2
  labels:
    app: podinfo2
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
